### ISSUE TITLE
404 Invalid Database

### ISSUE THREAD

**Issue by jerryngm** [marcocesarato/Database-Web-API#2]
Hi,
This is my config for MySQL. I installed your script on cPanel shared web hosting:
`define("__DATASETS__", serialize(array(
	'dataset' => array(
		'name'             => 'kaccboyp_ticket',
		'username'         => 'kaccboyp_ticket', // root is default
		'password'         => 'xxx', // root is default
		'server'           => 'localhost',  // localhost default
        'type'             => 'mysql',
        'port'             => 3306,
		'table_docs'       => $docs['dataset'],
		'table_list'       => array(), // Tables's whitelist (Allow only the tables in this list, if empty allow all)
		'table_blacklist'  => array(/*blacklist users table*/
			$users_table
		), // Tables's blacklist
		'column_list'      => array(), // Columns's whitelist (Allow only the columns in this list, if empty allow all)
		'column_blacklist' => array(), // Columns's blacklist
	),
)));`
This is my GET request URL: http://host/webapi/kaccboyp_ticket/TodayTicket.JSON

Please assist. 
Thank you!

**Comment by marcocesarato** [comment]
Hi,
You need just to change the dataset name to `kaccboyp_ticket` then change it like this:

 change
`define("__DATASETS__", serialize(array( 'dataset' => array( 'name' =....`
to 
`define("__DATASETS__", serialize(array( 'kaccboyp_ticket' => array( 'name' =....`

and another suggestion is to use lowercase link for better compatibilities like this:
http://host/webapi/kaccboyp_ticket/todayticket.json

I hope I was helpful
