### ISSUE TITLE
404 - Must Select a Database

### ISSUE THREAD

**Issue by enricogaggero** [marcocesarato/Database-Web-API#6]
Ciao Marco
sto provando il tuo progetto ma non riesco uscire fuori dal sistematico errore in oggetto.
Testing su WAMPSERVER 3.2.2. PHP 7.3.17
Database MySQL con nome : "testrestauto"
Una sola tabella "veicoli" 
il file config.php è così configurato :
define('__API_DATASETS__', serialize(array(
        'testrestauto' => array(
        'default' => true,
        'api' => true,
        'name' => 'testrestauto',        
        'username' => 'root',
        'password' => 'root',
        'server' => 'localhost',
        'port' => 3306,
        'ttl' => 1,
        'type' => 'mysql',
        'table_docs' => array(),
        'table_list' => array(),
        'table_blacklist' => array(),
        'column_list' => array(),
        'column_blacklist' => array(),
    ),
)));
Grazie sperando in un tuo supporto.
Enrico

**Comment by marcocesarato** [comment]
Ciao Enrico,
In poche parole l'url che devi raggiungere se tutto e configurato correttamente e il progetto si trova nella root www (altrimenti specificare la cartella) e' [http://localhost/testrestauto/veicoli.json](http://localhost/testrestauto/veicoli.json).
Per abilitare solo la tabella veicoli va inserite nell'array `table_list`. 
Se vuoi limitare anche le colonne vanno inserite anche in `column_list` con un array tipo:

```
array(
    'veicoli'  => // nome tabella
        array(
            'id',
            'targa' 
             //...
        )
)
```

Ti ho scritto dei commenti in maiuscolo cosi da evidenziare meglio i punti descritti.
Ecco la configurazione commentata:

```
// Datasets (list of database to connect)
define('__API_DATASETS__', serialize(array(
    // NOME DEL DATASET CHE PUOI DECIDERE SCEGLERE E CHE VISUALIZZERAI NELL'URL
    // QUESTO PERCHE E POSSIBILE COLLEGARE PIU DI UN DATABASE
    'testrestauto' => array( // URL ESEMPIO VEICOLI = http://localhost/api/testrestauto/veicoli.json
        'name' => 'testrestauto', // NOME DEL DATABASE 
        'username' => 'root', // root is default
        'password' => 'root', // root is default
        'server' => 'localhost',  // localhost default
        'port' => 3306, // 3306 is default
        'ttl' => 1, // Cache time to live. Disable cache (1 second only)
        'type' => 'mysql', // mysql is default
        'table_docs' => $docs['dataset'],
        'table_list' => array('veicoli'), // QUA INSERIRE LE TABELLE DA ABILITATE ALLA VISUALIZZAZIONE, SE VIENE SETTATA TUTTE LE ALTRE TABELLE VERRANNO OSCURATE
        // ALTRIMENTI USARE LA BLACKLIST PER FARE L'ESATTO CONTRARIO QUINDI VEDERE TUTTE LE TABELLE TRANNE QUELLE NELL'ARRAY table_blacklist
        'table_blacklist' => array(), // Tables's blacklist
        'column_list' => array(), // Columns's whitelist (Allow only the columns in this list, if empty allow all)
        'column_blacklist' => array(), // Columns's blacklist
    ),
)));

```

**Comment by enricogaggero** [comment]
Ciao Marco

Grazie per la tua gentilissima risposta ... mi sento stupido …

Ho incollato il codice che gentilmente mi hai inviato nel config.php

Il server php funziona altrimenti non avrei i messaggi di errore.

Il server mysql funziona altrimenti non potrei aprire il db e la tabella.

Ci ho lasciato gli occhi verificando gli errori di typo 

Continuo ad avere lo stesso errore …

Ho catturato delle schermate per essere più chiaro.

Il file dentro la cartella logs contiene questi messaggi 

[01-Jun-2020 15:10:42] [ERROR] [method GET] [url localhostDatabase-Web-API-master] [token ] [client 127.0.0.1]: 400 - Must select a Dataset

[01-Jun-2020 15:10:44] [ERROR] [method GET] [url localhostDatabase-Web-API-masterveicoli.json] [token ] [client 127.0.0.1]: 404 - Invalid Dataset

 

Ho scaricato lo zip del tuo progetto, ho unzippato dentro la cartella www di wamp (per fare le prove su macchine windows non ho mai avuto problemi), ho solo modificato il file config.php in base al manuale e ai tuoi consigli.

 

// NOME DEL DATASET CHE PUOI DECIDERE SCEGLERE E CHE VISUALIZZERAI NELL'URL QUESTO PERCHE E POSSIBILE COLLEGARE PIU DI UN DATABASE

// URL ESEMPIO VEICOLI = http://localhost/api/testrestauto/veicoli.json    

// dalla schermata ottengo il messaggio di errore da http://localhost/Database-Web-API-master/veicoli.json

 

define('__API_DATASETS__', serialize(array(

'testrestauto' => array( 

        'name' => 'testrestauto', // NOME DEL DATABASE 

        'username' => 'root', // root is default

        'password' => 'root', // root is default

        'server' => 'localhost',  // localhost default

        'port' => 3306, // 3306 is default

        'ttl' => 1, // Cache time to live. Disable cache (1 second only)

        'type' => 'mysql', // mysql is default

        'table_docs' => $docs['dataset'],

        'table_list' => array('veicoli'), // QUA INSERIRE LE TABELLE DA ABILITATE ALLA VISUALIZZAZIONE, SE VIENE SETTATA TUTTE LE ALTRE TABELLE VERRANNO OSCURATE

        // ALTRIMENTI USARE LA BLACKLIST PER FARE L'ESATTO CONTRARIO QUINDI VEDERE TUTTE LE TABELLE TRANNE QUELLE NELL'ARRAY table_blacklist

        'table_blacklist' => array(), // Tables's blacklist

        'column_list' => array(), // Columns's whitelist (Allow only the columns in this list, if empty allow all)

        'column_blacklist' => array(), // Columns's blacklist

    ),

)));

 

Non sono un fulmine in PHP (lavoro prevalentemente in Embarcadero Delphi e sto provando a realizzare delle app e volevo usare un server rest in php per interfacciarmi con mysql).

Grazie anticipatamente se potrai aiutarmi !

Enrico   

 

 

 

 

 

 

 

 

 

Da: Marco Cesarato <notifications@github.com> 
Inviato: lunedì 1 giugno 2020 16:41
A: marcocesarato/Database-Web-API <Database-Web-API@noreply.github.com>
Cc: enricogaggero <e.gaggero@egsoft.it>; Author <author@noreply.github.com>
Oggetto: Re: [marcocesarato/Database-Web-API] 404 - Must Select a Database (#6)

 

Ciao Enrico,
In poche parole l'url che devi raggiungere se tutto e configurato correttamente e http://localhost/api/testrestauto/veicoli.json.
Per abilitare solo la tabella veicoli va inserite nell'array table_list.
Se vuoi limitare anche le colonne vanno inserite anche in column_list con un array tipo:

array(
    'veicoli'  => // nome tabella
        array(
            'id',
            'targa' 
             //...
        )
)

Ti ho scritto dei commenti in maiuscolo cosi da evidenziare meglio i punti descritti.
Ecco la configurazione commentata:

// Datasets (list of database to connect)
define('__API_DATASETS__', serialize(array(
    // NOME DEL DATASET CHE PUOI DECIDERE SCEGLERE E CHE VISUALIZZERAI NELL'URL
    // QUESTO PERCHE E POSSIBILE COLLEGARE PIU DI UN DATABASE
    'testrestauto' => array( // URL ESEMPIO VEICOLI = http://localhost/api/testrestauto/veicoli.json
        'name' => 'testrestauto', // NOME DEL DATABASE 
        'username' => 'root', // root is default
        'password' => 'root', // root is default
        'server' => 'localhost',  // localhost default
        'port' => 3306, // 3306 is default
        'ttl' => 1, // Cache time to live. Disable cache (1 second only)
        'type' => 'mysql', // mysql is default
        'table_docs' => $docs['dataset'],
        'table_list' => array('veicoli'), // QUA INSERIRE LE TABELLE DA ABILITATE ALLA VISUALIZZAZIONE, SE VIENE SETTATA TUTTE LE ALTRE TABELLE VERRANNO OSCURATE
        // ALTRIMENTI USARE LA BLACKLIST PER FARE L'ESATTO CONTRARIO QUINDI VEDERE TUTTE LE TABELLE TRANNE QUELLE NELL'ARRAY table_blacklist
        'table_blacklist' => array(), // Tables's blacklist
        'column_list' => array(), // Columns's whitelist (Allow only the columns in this list, if empty allow all)
        'column_blacklist' => array(), // Columns's blacklist
    ),
)));

**Comment by marcocesarato** [comment]
Ok,
Si perche devi selezionare il dataset (in poche parole il database da cui estrarre i dati) quindi il link diventa: 
http://localhost/Database-Web-API-master/testrestauto/veicoli.json

testrestauto e il nome inserito nella costante __API_DATASETS__ come chiave

**Comment by enricogaggero** [comment]
Ok .. ora funziona .. Grazie mille,
